# Generated by Django 5.0.6 on 2026-10-08 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار')], max_length=20, verbose_name='نقش')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='accounts.business', verbose_name='کسب\u200cوکار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگوی AI',
                'verbose_name_plural': 'گفتگوهای AI',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True, verbose_name='متن تبدیل\u200cشده')),
                ('reply', models.TextField(blank=True, verbose_name='پاسخ دستیار')),
                ('actions', models.JSONField(blank=True, default=list, verbose_name='عملیات انجام\u200cشده')),
                ('error', models.TextField(blank=True, verbose_name='خطا')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='مدت (میلی\u200cثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_logs', to='accounts.business', verbose_name='کسب\u200cوکار')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ صوتی',
                'verbose_name_plural': 'لاگ\u200cهای صوتی',
                'ordering': ['-created_at'],
            },
        ),
    ]
